### ISSUE TITLE
factorissimo2-2.1.6 crashes game on multiple occasions

### ISSUE THREAD

**Issue by kugelzucker** [MagmaMcFry/Factorissimo2#9] opened 2017-05-23 18:07 UTC
running factorio-0.15.13 with some mods, among them upgrade planner in the most recent version (1.2.17)

first error was a crash when trying to upgrade a section while inside a factorissimo2-mk2 building. upgrading single entities worked fine, 2x4 as well, but the whole section crashed the game reliably. not sure if the size is the problem or something else.
screenshots:
![20170523195055_1](https://cloud.githubusercontent.com/assets/2139212/26368905/58a9dc6e-3ff3-11e7-8128-23db284c511a.jpg)
![20170523195101_1](https://cloud.githubusercontent.com/assets/2139212/26368904/58a8e9e4-3ff3-11e7-86fa-d39683f31d43.jpg)

second occasion while rotating placed underground belts:
![20170523200055_1](https://cloud.githubusercontent.com/assets/2139212/26368935/6dda780a-3ff3-11e7-821b-37f6efb483b6.jpg)

i can provide other details if needed!

**Comment by MagmaMcFry** [comment] 2017-05-23 18:36
Thanks for the report. Both of these issues were caused by Factorio 0.15.13 changing the API, breaking a lot of mods. Rotating underground belts works again in Factorissimo 2.1.7, the other issue needs to be fixed by Upgrade Planner.

**Closed by MagmaMcFry** 2017-05-23 18:36 UTC
